/**
 * Icon adapter — maps lucide-react icon names to Hugeicons equivalents.
 * Import from "@/lib/icons" instead of "lucide-react" for the modern icon set.
 *
 * Hugeicons: https://hugeicons.com — 4,600+ modern rounded icons
 */

export {
  // ── Navigation & Layout ──
  Home02Icon as Home,
  DashboardSpeed02Icon as LayoutDashboard,
  Menu01Icon as Menu,
  PanelLeftIcon as PanelLeft,
  PanelLeftCloseIcon as PanelLeftClose,
  ArrowLeft01Icon as ArrowLeft,
  ArrowRight01Icon as ArrowRight,
  ArrowUp01Icon as ArrowUp,
  ArrowDown01Icon as ArrowDown,
  ArrowUpDownIcon as ArrowUpDown,
  ArrowDown01Icon as ChevronDown,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowUp01Icon as ChevronUp,
  ArrowUp01Icon as ChevronUpIcon,
  ArrowLeft01Icon as ChevronLeft,
  ArrowLeft01Icon as ChevronLeftIcon,
  ArrowRight01Icon as ChevronRight,
  ArrowRight01Icon as ChevronRightIcon,
  UnfoldMoreIcon as ChevronsUpDown,
  LinkSquare02Icon as ExternalLink,
  LinkSquare02Icon as ExternalLinkIcon,
  GlobeIcon as Globe,
  LinkSquare01Icon as Link,
  Link04Icon as Link2,
  Layers01Icon as Layers,
  SlidersHorizontalIcon as SlidersHorizontal,
  CircleArrowUp01Icon as ArrowUpCircle,
  Login01Icon as ArrowRightFromLine,

  // ── Actions ──
  Search01Icon as Search,
  Search01Icon as SearchIcon,
  PlusSignIcon as Plus,
  Tick02Icon as Check,
  Tick02Icon as CheckIcon,
  TickDouble01Icon as CheckCheck,
  Cancel01Icon as X,
  Cancel01Icon as XIcon,
  Cancel01Icon as XCircle,
  Cancel01Icon as XOctagon,
  Copy01Icon as Copy,
  PencilIcon as Pencil,
  PencilEdit02Icon as Edit,
  PencilEdit02Icon as Edit3,
  Delete02Icon as Trash2,
  Download04Icon as Download,
  Upload04Icon as Upload,
  FloppyDiskIcon as Save,
  RefreshIcon as RefreshCw,
  Loading03Icon as Loader2,
  Loading03Icon as Loader2Icon,
  MoreHorizontalIcon as MoreHorizontal,
  MoreHorizontalIcon as MoreHorizontalIcon,
  ViewIcon as Eye,
  ViewOffSlashIcon as EyeOff,
  Drag01Icon as GripVertical,
  DragDropVerticalIcon as FolderKanban,
  FilterIcon as Filter,
  SquareIcon as Square,
  PlayIcon as Play,

  // ── Communication ──
  Mail01Icon as Mail,
  SentIcon as Send,
  Message01Icon as MessageSquare,
  MessageAdd01Icon as MessageSquarePlus,
  BubbleChatIcon as MessageCircle,
  Notification03Icon as Bell,
  NotificationOff01Icon as BellOff,
  Megaphone01Icon as Megaphone,
  Mic01Icon as Mic,
  MicOff01Icon as MicOff,
  SmartPhone01Icon as Smartphone,
  TelephoneIcon as Phone,
  CallOutgoing01Icon as PhoneCall,
  CallBlockedIcon as PhoneOff,
  Flag01Icon as Flag,

  // ── Content & Files ──
  File02Icon as File,
  File02Icon as FileText,
  FileExportIcon as FileBarChart,
  FileDownloadIcon as FileDown,
  FileRemoveIcon as FileX,
  Folder02Icon as FolderOpen,
  FolderImportIcon as FolderInput,
  Note01Icon as ClipboardList,
  ClipboardIcon as ClipboardCheck,
  PenTool01Icon as PenTool,
  Attachment01Icon as Paperclip,
  ImageAdd01Icon as ImagePlus,
  PinLocation01Icon as Pin,
  Location01Icon as MapPin,
  StickyNote01Icon as StickyNote,
  AddToListIcon as ListPlus,

  // ── Status & Feedback ──
  CheckmarkCircle02Icon as CheckCircle,
  CheckmarkCircle02Icon as CheckCircle2,
  CheckmarkCircle02Icon as CircleCheckIcon,
  CheckmarkSquare02Icon as CheckSquare,
  CheckmarkBadge01Icon as BadgeCheck,
  CheckmarkBadge01Icon as BadgeCheckIcon,
  AlertCircleIcon as AlertCircle,
  Alert02Icon as AlertTriangle,
  Alert02Icon as TriangleAlertIcon,
  InformationCircleIcon as Info,
  InformationCircleIcon as InfoIcon,
  Cancel01Icon as OctagonXIcon,
  CircleIcon as Circle,
  MinusSignIcon as Minus,

  // ── Business & Finance ──
  Dollar02Icon as DollarSign,
  Briefcase01Icon as Briefcase,
  Analytics02Icon as Activity,
  BarChartIcon as BarChart3,
  ChartHistogramIcon as TrendingUp,
  ChartDecreaseIcon as TrendingDown,
  Target02Icon as Target,
  Shield01Icon as Shield,
  Shield01Icon as ShieldCheck,
  LockIcon as Lock,
  PercentIcon as Percent,
  ReceiptDollarIcon as Receipt,

  // ── Education ──
  GraduationScrollIcon as GraduationCap,
  BookOpen02Icon as BookOpen,
  School01Icon as School,
  Building04Icon as Building2,
  Award02Icon as Award,
  Award02Icon as Trophy,
  CrownIcon as Crown,
  Medal01Icon as Medal,
  BrainIcon as Brain,
  CompassIcon as Compass,
  TestTube01Icon as TestTube,

  // ── Calendar & Time ──
  Calendar03Icon as Calendar,
  Calendar03Icon as CalendarDays,
  CalendarAdd01Icon as CalendarPlus,
  CalendarCheckIn01Icon as CalendarRange,
  Clock02Icon as Clock,
  Clock02Icon as CalendarClock,
  WorkHistoryIcon as History,

  // ── People ──
  User02Icon as User,
  UserAdd01Icon as UserPlus,
  UserCheck01Icon as UserCheck,
  UserMinus01Icon as UserMinus,
  UserMultiple02Icon as Users,
  UserCircle02Icon as CircleUserRound,

  // ── Media & Display ──
  Video02Icon as Video,
  VideoOffIcon as VideoOff,
  Moon02Icon as Moon,
  Sun03Icon as Sun,
  ComputerIcon as Monitor,
  ComputerPhoneSyncIcon as MonitorUp,
  ComputerIcon as MonitorIcon,
  Bookmark02Icon as Bookmark,

  // ── AI & Creative ──
  SparklesIcon as Sparkles,
  AiChat02Icon as Bot,
  BulbIcon as Lightbulb,
  Rocket01Icon as Rocket,
  PaintBrush04Icon as Palette,
  StarIcon as Star,
  FavouriteIcon as Heart,
  HandPrayerIcon as HandHeart,
  Dumbbell03Icon as Dumbbell,
  TestTube01Icon as FlaskConical,
  Task01Icon as ListTodo,
  TaskDone01Icon as ListChecks,
  ThumbsUpIcon as ThumbsUp,
  ZapIcon as Zap,
  FlashIcon as Bolt,

  // ── System ──
  Settings02Icon as Settings,
  Logout01Icon as LogOut,
  LifebuoyIcon as LifeBuoy,
  ComputerTerminal01Icon as Terminal,

  // ── Misc ──
  SortingUpIcon as FileUp,
  FilterHorizontalIcon as FilterHorizontal,
} from "hugeicons-react"

// Type alias for icon components
import type { FC, SVGProps } from "react"
export type LucideIcon = FC<SVGProps<SVGSVGElement> & { size?: number | string }>
export type LucideProps = SVGProps<SVGSVGElement> & { size?: number | string }
