import type { ComponentType } from "react"
import {
  LayoutDashboard,
  CalendarDays,
  Bot,
  CheckSquare,
  BookOpen,
  Trophy,
  Search,
  Star,
  GraduationCap,
  DollarSign,
  PenTool,
  Mail,
  FolderOpen,
  Activity,
  Bell,
  Clock,
  CheckCircle,
  MapPin,
  Megaphone,
  UserPlus,
  UserCheck,
  Layers,
  School,
  Building2,
  Award,
  ListTodo,
  Briefcase,
  ClipboardCheck,
  FileText,
  BarChart3,
  LifeBuoy,
  Settings,
  Shield,
  Users,
  Video,
  MessageSquare,
  User,
} from "@/lib/icons"

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type IconComponent = ComponentType<any>

const iconMap: Record<string, IconComponent> = {
  LayoutDashboard,
  CalendarDays,
  Bot,
  CheckSquare,
  BookOpen,
  Trophy,
  Search,
  Star,
  GraduationCap,
  DollarSign,
  PenTool,
  Mail,
  FolderOpen,
  Activity,
  Bell,
  Clock,
  CheckCircle,
  MapPin,
  Megaphone,
  UserPlus,
  UserCheck,
  Layers,
  School,
  Building2,
  Award,
  ListTodo,
  Briefcase,
  ClipboardCheck,
  FileText,
  BarChart3,
  LifeBuoy,
  Settings,
  Shield,
  Users,
  Video,
  MessageSquare,
  User,
}

export function NavIcon({ name, className = "h-4 w-4" }: { name: string; className?: string }) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon className={className} />
}
